import React,{useEffect,useMemo,useState} from 'react';
type Entry={key:string;name:string;part_type?:string;instrument_type?:string};
const parts=['body','neck','fretboard','electronics','hardware'];
const presets:any={Novice:{luthiery:10,woodworking:10,fretwork:10,instrument_electronics:10,instrument_finishing:10},Competent:{luthiery:50,woodworking:45,fretwork:45,instrument_electronics:45,instrument_finishing:45},Master:{luthiery:100,woodworking:100,fretwork:100,instrument_electronics:100,instrument_finishing:100}};
export default function LuthieryTestBench(){
 const [cat,setCat]=useState<any>(null),[type,setType]=useState('guitar'),[shape,setShape]=useState(''),[sel,setSel]=useState<any>({}),[skills,setSkills]=useState(presets.Competent),[workshop,setWorkshop]=useState(70),[result,setResult]=useState<any>(null),[error,setError]=useState('');
 useEffect(()=>{fetch('/admin/luthiery/catalogue').then(r=>r.json()).then(setCat).catch(()=>setError('Unable to load Luthiery catalogue.'))},[]);
 const shapes=useMemo(()=>cat?.shapes?.filter((x:Entry)=>x.instrument_type===type)||[],[cat,type]);
 const setPart=(p:string,k:string,v:string)=>setSel((s:any)=>({...s,[p]:{...(s[p]||{}),[k]:v||null}}));
 const run=async()=>{setError('');setResult(null);const res=await fetch('/admin/luthiery/demo/craft',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({instrument_type:type,shape_key:shape,selections:sel,skills,workshop_score:workshop,seed_token:'admin-ui-demo'})});const d=await res.json();if(!res.ok)setError(d.detail||'Preview failed');else setResult(d)};
 if(!cat)return <div className="p-4">{error||'Loading Luthiery test bench…'}</div>;
 return <div className="space-y-5 max-w-6xl"><div><h1 className="text-2xl font-bold">Luthiery Crafting Test Bench</h1><p className="text-sm text-gray-600">Dry-run real crafting rules. No materials, money or instruments are changed.</p></div>
 <div className="flex gap-2">{Object.keys(presets).map(k=><button key={k} onClick={()=>setSkills(presets[k])} className="px-3 py-2 border rounded">{k}</button>)}</div>
 <div className="grid md:grid-cols-3 gap-3"><label>Instrument<select className="block border p-2 w-full" value={type} onChange={e=>{setType(e.target.value);setShape('')}}><option>guitar</option><option>bass</option></select></label><label>Shape<select className="block border p-2 w-full" value={shape} onChange={e=>setShape(e.target.value)}><option value="">Select…</option>{shapes.map((x:Entry)=><option key={x.key} value={x.key}>{x.name}</option>)}</select></label><label>Workshop {workshop}<input className="block w-full" type="range" min="0" max="100" value={workshop} onChange={e=>setWorkshop(+e.target.value)}/></label></div>
 <div className="grid md:grid-cols-2 gap-3">{parts.map(p=><div key={p} className="border rounded p-3"><h2 className="font-semibold capitalize">{p}</h2><select className="border p-2 w-full my-1" onChange={e=>setPart(p,'material_key',e.target.value)}><option value="">Material…</option>{cat.materials.map((x:Entry)=><option key={x.key} value={x.key}>{x.name}</option>)}</select><select className="border p-2 w-full" onChange={e=>setPart(p,'component_key',e.target.value)}><option value="">No component</option>{cat.components.filter((x:Entry)=>x.part_type===p).map((x:Entry)=><option key={x.key} value={x.key}>{x.name}</option>)}</select></div>)}</div>
 <button onClick={run} disabled={!shape||parts.some(p=>!sel[p]?.material_key)} className="px-5 py-3 rounded bg-gray-900 text-white disabled:opacity-40">Run crafting preview</button>{error&&<p className="text-red-700">{error}</p>}
 {result&&<div className="border rounded p-4"><h2 className="text-xl font-bold">{result.quality_tier} — {result.quality_score}/100</h2><p>Material {result.material_score} · Specialist {result.specialist_score} · Workshop {result.workshop_score}</p><h3 className="font-semibold mt-3">Traits</h3><p>{result.traits?.join(', ')||'None'}</p><h3 className="font-semibold mt-3">Gameplay modifiers</h3><pre className="text-xs overflow-auto bg-gray-100 p-3">{JSON.stringify(result.gameplay_modifiers,null,2)}</pre></div>}</div>
}