[build]
  command = "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && export PATH=\"$HOME/.cargo/bin:$PATH\" && pip install -r requirements.txt && npm ci --prefix frontend && npm run build --prefix frontend"
  publish = "frontend/pages"

[build.environment]
  NODE_VERSION = "20.11.1"
  REACT_APP_API_BASE = "https://backend.example.com"

[[redirects]]
  from = "/api/*"
  to   = "https://backend.example.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
