[build]
  base = "frontend"
  publish = "frontend/build"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_API_BASE = "https://backend.example.com"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:8000/api/:splat"
  status = 200
  force = true
