[build]
  command = ""
  publish = "frontend/pages"

[build.environment]
  NODE_VERSION = "20.11.1"
  REACT_APP_API_BASE = "https://backend.example.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
